# must copy this file to output dir
# where publishing this project

# FROM microsoft/dotnet:3.1-aspnetcore-runtime
FROM mcr.microsoft.com/dotnet/aspnet:3.1-alpine
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY . .
ENTRYPOINT ["dotnet", "Talking.Api.dll"]